/*  CoffeeSoft :: catalogo de iconos Lucide para el selector (cs-icon-picker.js).

    NOMBRES CANONICOS en kebab-case, que es lo que se guarda en modules.icon y
    sections.icon y lo que lee data-lucide. Los alias viejos (bar-chart-3,
    home, users-2...) siguen funcionando en la pagina porque lucide los
    resuelve, pero NO se ofrecen aqui: las paginas cargan lucide@latest y un
    alias es lo primero que una version nueva puede dejar de reconocer.

    Generado desde lucide v1.46.0 (dist/umd/lucide.js): son los nombres de las
    constantes del paquete pasados a kebab-case, sin alias. Para regenerarlo
    con una version nueva basta con volver a correr esa conversion; el selector
    ademas esconde solo los que la lucide cargada ya no traiga y agrega los que
    traiga de mas, asi que una lista atrasada no rompe nada.

    CS_ICONS_ES es un diccionario espanol -> palabras del nombre en ingles para
    que el buscador entienda "usuario", "dinero" o "calendario". No pretende
    ser completo: cubre el vocabulario del ERP.
*/
window.CS_ICONS_VERSION = '1.46.0';

window.CS_ICONS = [
    'a-arrow-down', 'a-arrow-up', 'a-large-small', 'accessibility', 'activity', 'ad', 'air-vent', 'airplay',
    'alarm-clock', 'alarm-clock-check', 'alarm-clock-minus', 'alarm-clock-off', 'alarm-clock-plus',
    'alarm-smoke', 'align-center-horizontal', 'align-center-vertical', 'align-end-horizontal',
    'align-end-vertical', 'align-horizontal-distribute-center', 'align-horizontal-distribute-end',
    'align-horizontal-distribute-start', 'align-horizontal-justify-center', 'align-horizontal-justify-end',
    'align-horizontal-justify-start', 'align-horizontal-space-around', 'align-horizontal-space-between',
    'align-start-horizontal', 'align-start-vertical', 'align-vertical-distribute-center',
    'align-vertical-distribute-end', 'align-vertical-distribute-start', 'align-vertical-justify-center',
    'align-vertical-justify-end', 'align-vertical-justify-start', 'align-vertical-space-around',
    'align-vertical-space-between', 'ambulance', 'ampersand', 'ampersands', 'amphora', 'anchor', 'angle',
    'antenna', 'anvil', 'aperture', 'app-window', 'app-window-mac', 'apple', 'archive', 'archive-restore',
    'archive-x', 'armchair', 'arrow-big-down', 'arrow-big-down-dash', 'arrow-big-left', 'arrow-big-left-dash',
    'arrow-big-right', 'arrow-big-right-dash', 'arrow-big-up', 'arrow-big-up-dash', 'arrow-down',
    'arrow-down-01', 'arrow-down-10', 'arrow-down-a-z', 'arrow-down-from-line', 'arrow-down-left',
    'arrow-down-narrow-wide', 'arrow-down-right', 'arrow-down-to-dot', 'arrow-down-to-line', 'arrow-down-up',
    'arrow-down-wide-narrow', 'arrow-down-z-a', 'arrow-left', 'arrow-left-from-line', 'arrow-left-right',
    'arrow-left-to-line', 'arrow-right', 'arrow-right-from-line', 'arrow-right-left', 'arrow-right-to-line',
    'arrow-up', 'arrow-up-01', 'arrow-up-10', 'arrow-up-a-z', 'arrow-up-down', 'arrow-up-from-dot',
    'arrow-up-from-line', 'arrow-up-left', 'arrow-up-narrow-wide', 'arrow-up-right', 'arrow-up-to-line',
    'arrow-up-wide-narrow', 'arrow-up-z-a', 'arrows-up-from-line', 'asterisk', 'astroid', 'at-sign', 'atom',
    'audio-lines', 'audio-lines-off', 'audio-lines-x', 'audio-waveform', 'award', 'axe', 'axis-3d', 'baby',
    'backpack', 'badge', 'badge-alert', 'badge-cent', 'badge-check', 'badge-dollar-sign', 'badge-euro',
    'badge-indian-rupee', 'badge-info', 'badge-japanese-yen', 'badge-minus', 'badge-percent', 'badge-plus',
    'badge-pound-sterling', 'badge-question-mark', 'badge-russian-ruble', 'badge-swiss-franc',
    'badge-turkish-lira', 'badge-x', 'baggage-claim', 'balloon', 'ban', 'banana', 'bandage', 'banknote',
    'banknote-arrow-down', 'banknote-arrow-up', 'banknote-check', 'banknote-x', 'barcode', 'barrel', 'baseline',
    'bath', 'battery', 'battery-charging', 'battery-full', 'battery-low', 'battery-medium', 'battery-plus',
    'battery-warning', 'beaker', 'bean', 'bean-off', 'bed', 'bed-double', 'bed-single', 'beef', 'beef-off',
    'beer', 'beer-off', 'bell', 'bell-check', 'bell-dot', 'bell-electric', 'bell-minus', 'bell-off',
    'bell-plus', 'bell-ring', 'between-horizontal-end', 'between-horizontal-start', 'between-vertical-end',
    'between-vertical-start', 'biceps-flexed', 'bike', 'binary', 'binoculars', 'biohazard', 'bird', 'birdhouse',
    'bitcoin', 'blend', 'blender', 'blinds', 'blocks', 'bluetooth', 'bluetooth-connected', 'bluetooth-off',
    'bluetooth-searching', 'bold', 'bolt', 'bomb', 'bone', 'bone-fracture', 'book', 'book-a', 'book-alert',
    'book-audio', 'book-bookmark', 'book-check', 'book-copy', 'book-dashed', 'book-down', 'book-headphones',
    'book-heart', 'book-image', 'book-key', 'book-lock', 'book-minus', 'book-open', 'book-open-check',
    'book-open-text', 'book-plus', 'book-search', 'book-text', 'book-type', 'book-up', 'book-up-2', 'book-user',
    'book-x', 'bookmark', 'bookmark-check', 'bookmark-minus', 'bookmark-off', 'bookmark-plus', 'bookmark-x',
    'boom-box', 'bot', 'bot-message-square', 'bot-off', 'bottle-wine', 'bow-arrow', 'box', 'boxes', 'braces',
    'brackets', 'brain', 'brain-circuit', 'brain-cog', 'brick-wall', 'brick-wall-fire', 'brick-wall-shield',
    'bridge', 'briefcase', 'briefcase-business', 'briefcase-conveyor-belt', 'briefcase-medical',
    'bring-to-front', 'broccoli', 'broom', 'broom-sparkles', 'brush', 'brush-cleaning', 'bubbles', 'bug',
    'bug-off', 'bug-play', 'building', 'building-complex', 'building-complex-plus', 'bus', 'bus-front', 'cable',
    'cable-car', 'cake', 'cake-slice', 'calculator', 'calendar', 'calendar-1', 'calendar-arrow-down',
    'calendar-arrow-up', 'calendar-check', 'calendar-check-2', 'calendar-chevrons-right', 'calendar-clock',
    'calendar-cog', 'calendar-days', 'calendar-fold', 'calendar-heart', 'calendar-minus', 'calendar-minus-2',
    'calendar-off', 'calendar-plus', 'calendar-plus-2', 'calendar-range', 'calendar-search', 'calendar-sync',
    'calendar-x', 'calendar-x-2', 'calendars', 'camera', 'camera-off', 'can', 'can-soda', 'candy', 'candy-cane',
    'candy-off', 'cannabis', 'cannabis-off', 'captions', 'captions-off', 'car', 'car-battery', 'car-front',
    'car-taxi-front', 'caravan', 'card-sim', 'carrot', 'carton', 'carton-off', 'case-lower', 'case-sensitive',
    'case-upper', 'cassette-tape', 'cast', 'castle', 'cat', 'cctv', 'cctv-off', 'chart-area', 'chart-bar',
    'chart-bar-big', 'chart-bar-decreasing', 'chart-bar-increasing', 'chart-bar-stacked', 'chart-candlestick',
    'chart-column', 'chart-column-big', 'chart-column-decreasing', 'chart-column-increasing',
    'chart-column-stacked', 'chart-gantt', 'chart-line', 'chart-network', 'chart-no-axes-column',
    'chart-no-axes-column-decreasing', 'chart-no-axes-column-increasing', 'chart-no-axes-combined',
    'chart-no-axes-gantt', 'chart-pie', 'chart-scatter', 'chart-spline', 'check', 'check-check', 'check-line',
    'chef-hat', 'cherry', 'chess-bishop', 'chess-king', 'chess-knight', 'chess-pawn', 'chess-queen',
    'chess-rook', 'chevron-down', 'chevron-first', 'chevron-last', 'chevron-left', 'chevron-right',
    'chevron-up', 'chevrons-down', 'chevrons-down-up', 'chevrons-left', 'chevrons-left-right',
    'chevrons-left-right-ellipsis', 'chevrons-right', 'chevrons-right-left', 'chevrons-up', 'chevrons-up-down',
    'church', 'cigarette', 'cigarette-off', 'circle', 'circle-alert', 'circle-arrow-down', 'circle-arrow-left',
    'circle-arrow-out-down-left', 'circle-arrow-out-down-right', 'circle-arrow-out-up-left',
    'circle-arrow-out-up-right', 'circle-arrow-right', 'circle-arrow-up', 'circle-check', 'circle-check-big',
    'circle-chevron-down', 'circle-chevron-left', 'circle-chevron-right', 'circle-chevron-up', 'circle-dashed',
    'circle-dashed-check', 'circle-divide', 'circle-dollar-sign', 'circle-dot', 'circle-dot-dashed',
    'circle-ellipsis', 'circle-equal', 'circle-euro', 'circle-fading-arrow-up', 'circle-fading-plus',
    'circle-gauge', 'circle-minus', 'circle-off', 'circle-parking', 'circle-parking-off', 'circle-pause',
    'circle-percent', 'circle-pile', 'circle-play', 'circle-plus', 'circle-pound-sterling', 'circle-power',
    'circle-question-mark', 'circle-slash', 'circle-slash-2', 'circle-small', 'circle-star', 'circle-stop',
    'circle-user', 'circle-user-round', 'circle-x', 'circuit-board', 'citrus', 'clapperboard', 'clef-alto',
    'clef-bass', 'clef-treble', 'clipboard', 'clipboard-check', 'clipboard-clock', 'clipboard-copy',
    'clipboard-list', 'clipboard-minus', 'clipboard-paste', 'clipboard-pen', 'clipboard-pen-line',
    'clipboard-plus', 'clipboard-type', 'clipboard-x', 'clock', 'clock-1', 'clock-10', 'clock-11', 'clock-12',
    'clock-2', 'clock-3', 'clock-4', 'clock-5', 'clock-6', 'clock-7', 'clock-8', 'clock-9', 'clock-alert',
    'clock-arrow-down', 'clock-arrow-left', 'clock-arrow-right', 'clock-arrow-up', 'clock-check',
    'clock-fading', 'clock-plus', 'closed-caption', 'cloud', 'cloud-alert', 'cloud-backup', 'cloud-check',
    'cloud-cog', 'cloud-download', 'cloud-drizzle', 'cloud-fog', 'cloud-hail', 'cloud-lightning', 'cloud-moon',
    'cloud-moon-rain', 'cloud-off', 'cloud-rain', 'cloud-rain-wind', 'cloud-snow', 'cloud-sun',
    'cloud-sun-rain', 'cloud-sync', 'cloud-upload', 'cloudy', 'clover', 'club', 'code', 'code-xml', 'coffee',
    'cog', 'coins', 'columns-2', 'columns-3', 'columns-3-cog', 'columns-4', 'combine', 'command', 'compass',
    'component', 'computer', 'concierge-bell', 'cone', 'construction', 'contact', 'contact-round', 'container',
    'contrast', 'cookie', 'cooking-pot', 'copy', 'copy-check', 'copy-minus', 'copy-plus', 'copy-slash',
    'copy-x', 'copyleft', 'copyright', 'corner-down-left', 'corner-down-right', 'corner-left-down',
    'corner-left-up', 'corner-right-down', 'corner-right-up', 'corner-up-left', 'corner-up-right', 'cpu',
    'creative-commons', 'credit-card', 'credit-card-check', 'credit-card-minus', 'credit-card-plus',
    'credit-card-reader', 'credit-card-x', 'croissant', 'crop', 'cross', 'crosshair', 'crown', 'cuboid',
    'cup-soda', 'currency', 'cylinder', 'dam', 'database', 'database-arrow-down', 'database-arrow-up',
    'database-backup', 'database-check', 'database-minus', 'database-plus', 'database-search', 'database-x',
    'database-zap', 'decimals-arrow-left', 'decimals-arrow-right', 'delete', 'dessert', 'diameter', 'diamond',
    'diamond-minus', 'diamond-percent', 'diamond-plus', 'dice-1', 'dice-2', 'dice-3', 'dice-4', 'dice-5',
    'dice-6', 'dices', 'diff', 'disc', 'disc-2', 'disc-3', 'disc-album', 'divide', 'dna', 'dna-off', 'dock',
    'dog', 'dollar-sign', 'dome', 'donut', 'door-closed', 'door-closed-locked', 'door-open', 'door-stairwell',
    'dot', 'download', 'drafting-compass', 'drama', 'drill', 'drone', 'droplet', 'droplet-off', 'droplets',
    'drum', 'drumstick', 'dumbbell', 'ear', 'ear-off', 'earth', 'earth-lock', 'eclipse', 'egg', 'egg-fried',
    'egg-off', 'eject', 'ellipse', 'ellipsis', 'ellipsis-vertical', 'engine', 'equal', 'equal-approximately',
    'equal-approximately-not', 'equal-not', 'eraser', 'ethernet-port', 'euro', 'ev-charger', 'expand',
    'external-link', 'eye', 'eye-closed', 'eye-dashed', 'eye-off', 'face-angry', 'face-expressionless',
    'face-grinning', 'face-neutral', 'face-slightly-frowning', 'face-slightly-smiling',
    'face-slightly-smiling-plus', 'factory', 'fan', 'fast-forward', 'feather', 'fence', 'ferris-wheel', 'file',
    'file-archive', 'file-axis-3d', 'file-badge', 'file-box', 'file-braces', 'file-braces-corner',
    'file-chart-column', 'file-chart-column-increasing', 'file-chart-line', 'file-chart-pie', 'file-check',
    'file-check-corner', 'file-clock', 'file-code', 'file-code-corner', 'file-cog', 'file-diff', 'file-digit',
    'file-down', 'file-exclamation-point', 'file-headphone', 'file-heart', 'file-image', 'file-input',
    'file-key', 'file-lock', 'file-minus', 'file-minus-corner', 'file-music', 'file-output', 'file-pen',
    'file-pen-line', 'file-play', 'file-plus', 'file-plus-corner', 'file-question-mark', 'file-scan',
    'file-search', 'file-search-corner', 'file-signal', 'file-sliders', 'file-spreadsheet', 'file-stack',
    'file-symlink', 'file-terminal', 'file-text', 'file-type', 'file-type-corner', 'file-up', 'file-user',
    'file-video-camera', 'file-volume', 'file-x', 'file-x-corner', 'files', 'film', 'fingerprint-pattern',
    'fire-extinguisher', 'fish', 'fish-off', 'fish-symbol', 'fishing-hook', 'fishing-rod', 'flag', 'flag-off',
    'flag-triangle-left', 'flag-triangle-right', 'flame', 'flame-kindling', 'flashlight', 'flashlight-off',
    'flask-conical', 'flask-conical-off', 'flask-round', 'flower', 'flower-2', 'focus', 'fold-horizontal',
    'fold-vertical', 'folder', 'folder-archive', 'folder-bookmark', 'folder-check', 'folder-clock',
    'folder-closed', 'folder-code', 'folder-cog', 'folder-dot', 'folder-down', 'folder-git', 'folder-git-2',
    'folder-heart', 'folder-input', 'folder-kanban', 'folder-key', 'folder-lock', 'folder-minus', 'folder-open',
    'folder-open-dot', 'folder-output', 'folder-pen', 'folder-plus', 'folder-root', 'folder-search',
    'folder-search-2', 'folder-symlink', 'folder-sync', 'folder-tree', 'folder-up', 'folder-x', 'folders',
    'footprints', 'forklift', 'form', 'forward', 'frame', 'fuel', 'fullscreen', 'funnel', 'funnel-plus',
    'funnel-x', 'galaxy', 'gallery-horizontal', 'gallery-horizontal-end', 'gallery-thumbnails',
    'gallery-vertical', 'gallery-vertical-end', 'gamepad', 'gamepad-2', 'gamepad-directional', 'gap-horizontal',
    'gap-vertical', 'gauge', 'gavel', 'gem', 'georgian-lari', 'germ', 'germ-off', 'ghost', 'gift', 'git-branch',
    'git-branch-minus', 'git-branch-plus', 'git-commit-horizontal', 'git-commit-vertical', 'git-compare',
    'git-compare-arrows', 'git-fork', 'git-graph', 'git-merge', 'git-merge-conflict', 'git-pull-request',
    'git-pull-request-arrow', 'git-pull-request-closed', 'git-pull-request-create',
    'git-pull-request-create-arrow', 'git-pull-request-draft', 'glass-water', 'glasses', 'globe', 'globe-check',
    'globe-code', 'globe-lock', 'globe-off', 'globe-x', 'goal', 'gpu', 'graduation-cap', 'grape', 'grid-2x2',
    'grid-2x2-check', 'grid-2x2-plus', 'grid-2x2-x', 'grid-3x2', 'grid-3x3', 'grip', 'grip-horizontal',
    'grip-vertical', 'group', 'guitar', 'ham', 'hamburger', 'hammer', 'hand', 'hand-coins', 'hand-fist',
    'hand-grab', 'hand-heart', 'hand-helping', 'hand-metal', 'hand-platter', 'handbag', 'handshake',
    'hard-drive', 'hard-drive-download', 'hard-drive-upload', 'hard-hat', 'hash', 'hat-glasses', 'haze', 'hd',
    'hdmi-port', 'heading', 'heading-1', 'heading-2', 'heading-3', 'heading-4', 'heading-5', 'heading-6',
    'headphone-off', 'headphones', 'headset', 'heart', 'heart-crack', 'heart-handshake', 'heart-minus',
    'heart-off', 'heart-plus', 'heart-pulse', 'heart-x', 'heater', 'helicopter', 'hexagon', 'highlighter',
    'hop', 'hop-off', 'hospital', 'hotel', 'hourglass', 'hourglass-cog', 'house', 'house-heart', 'house-plug',
    'house-plus', 'house-wifi', 'houses', 'ice-cream-bowl', 'ice-cream-cone', 'id-card', 'id-card-lanyard',
    'image', 'image-down', 'image-minus', 'image-off', 'image-play', 'image-plus', 'image-up', 'image-upscale',
    'images', 'import', 'inbox', 'indian-rupee', 'infinity', 'info', 'inspection-panel', 'italic',
    'iteration-ccw', 'iteration-cw', 'iv-bag', 'japanese-yen', 'joystick', 'kanban', 'kayak', 'key',
    'key-round', 'key-square', 'keyboard', 'keyboard-music', 'keyboard-off', 'lamp', 'lamp-ceiling',
    'lamp-desk', 'lamp-floor', 'lamp-wall-down', 'lamp-wall-up', 'land-plot', 'landmark', 'languages', 'laptop',
    'laptop-minimal', 'laptop-minimal-check', 'lasso', 'lasso-select', 'layer-arrow-down', 'layer-arrow-up',
    'layers', 'layers-2', 'layers-arrow-down', 'layers-arrow-up', 'layers-minus', 'layers-plus',
    'layout-arrow-down', 'layout-arrow-right', 'layout-dashboard', 'layout-freeform', 'layout-grid',
    'layout-list', 'layout-panel-left', 'layout-panel-top', 'layout-template', 'leaf', 'leafy-green', 'lectern',
    'lens-concave', 'lens-convex', 'library', 'library-big', 'life-buoy', 'ligature', 'lightbulb',
    'lightbulb-off', 'lighthouse', 'line-dot-right-horizontal', 'line-squiggle', 'line-style', 'link', 'link-2',
    'link-2-off', 'list', 'list-check', 'list-checks', 'list-chevrons-down-up', 'list-chevrons-up-down',
    'list-clock', 'list-collapse', 'list-end', 'list-filter', 'list-filter-plus', 'list-indent-decrease',
    'list-indent-increase', 'list-minus', 'list-music', 'list-ordered', 'list-plus', 'list-restart',
    'list-sort-ascending', 'list-sort-descending', 'list-start', 'list-todo', 'list-tree', 'list-video',
    'list-x', 'loader', 'loader-circle', 'loader-pinwheel', 'locate', 'locate-fixed', 'locate-off', 'lock',
    'lock-keyhole', 'lock-keyhole-open', 'lock-open', 'log-in', 'log-out', 'logs', 'lollipop', 'luggage',
    'magnet', 'mail', 'mail-badge', 'mail-check', 'mail-clock', 'mail-minus', 'mail-open', 'mail-pen',
    'mail-plus', 'mail-question-mark', 'mail-search', 'mail-warning', 'mail-x', 'mailbox', 'mails', 'map',
    'map-minus', 'map-pin', 'map-pin-check', 'map-pin-check-inside', 'map-pin-house', 'map-pin-minus',
    'map-pin-minus-inside', 'map-pin-off', 'map-pin-pen', 'map-pin-plus', 'map-pin-plus-inside',
    'map-pin-search', 'map-pin-x', 'map-pin-x-inside', 'map-pinned', 'map-plus', 'mars', 'mars-stroke',
    'martini', 'maximize', 'maximize-2', 'medal', 'megaphone', 'megaphone-off', 'memory-stick', 'menu', 'merge',
    'message-circle', 'message-circle-check', 'message-circle-code', 'message-circle-dashed',
    'message-circle-dashed-check', 'message-circle-heart', 'message-circle-more', 'message-circle-off',
    'message-circle-plus', 'message-circle-question-mark', 'message-circle-reply', 'message-circle-warning',
    'message-circle-x', 'message-square', 'message-square-check', 'message-square-code',
    'message-square-dashed', 'message-square-diff', 'message-square-dot', 'message-square-heart',
    'message-square-lock', 'message-square-more', 'message-square-off', 'message-square-plus',
    'message-square-quote', 'message-square-reply', 'message-square-share', 'message-square-text',
    'message-square-warning', 'message-square-x', 'messages-circle', 'messages-square', 'metronome', 'mic',
    'mic-audio-lines', 'mic-off', 'mic-signal', 'mic-vocal', 'microchip', 'microscope', 'microwave',
    'midi-port', 'milestone', 'milk', 'milk-off', 'minimize', 'minimize-2', 'minus', 'mirror-rectangular',
    'mirror-round', 'monitor', 'monitor-check', 'monitor-cloud', 'monitor-cog', 'monitor-dot', 'monitor-down',
    'monitor-off', 'monitor-pause', 'monitor-pc', 'monitor-play', 'monitor-smartphone', 'monitor-speaker',
    'monitor-stop', 'monitor-up', 'monitor-x', 'moon', 'moon-star', 'mop', 'mop-sparkles', 'mosque',
    'motorbike', 'mountain', 'mountain-snow', 'mouse', 'mouse-left', 'mouse-off', 'mouse-pointer',
    'mouse-pointer-2', 'mouse-pointer-2-off', 'mouse-pointer-ban', 'mouse-pointer-click', 'mouse-right',
    'mouth', 'mouth-off', 'move', 'move-3d', 'move-diagonal', 'move-diagonal-2', 'move-down', 'move-down-left',
    'move-down-right', 'move-horizontal', 'move-left', 'move-right', 'move-up', 'move-up-left', 'move-up-right',
    'move-vertical', 'music', 'music-2', 'music-3', 'music-4', 'navigation', 'navigation-2', 'navigation-2-off',
    'navigation-off', 'network', 'newspaper', 'nfc', 'non-binary', 'notebook', 'notebook-dot', 'notebook-pen',
    'notebook-tabs', 'notebook-text', 'notepad-text', 'notepad-text-dashed', 'nut', 'nut-off', 'octagon',
    'octagon-alert', 'octagon-minus', 'octagon-pause', 'octagon-x', 'omega', 'option', 'orbit', 'origami',
    'package', 'package-2', 'package-check', 'package-minus', 'package-open', 'package-plus', 'package-search',
    'package-x', 'paint-bucket', 'paint-roller', 'paintbrush', 'paintbrush-vertical', 'palette', 'panda',
    'panel-bottom', 'panel-bottom-close', 'panel-bottom-dashed', 'panel-bottom-open', 'panel-left',
    'panel-left-close', 'panel-left-dashed', 'panel-left-open', 'panel-left-right-dashed', 'panel-right',
    'panel-right-close', 'panel-right-dashed', 'panel-right-open', 'panel-top', 'panel-top-bottom-dashed',
    'panel-top-close', 'panel-top-dashed', 'panel-top-open', 'panels-left-bottom', 'panels-right-bottom',
    'panels-top-left', 'paper-bag', 'paperclip', 'parasol', 'parentheses', 'park', 'parking-meter',
    'party-popper', 'pause', 'paw-print', 'pc-case', 'pen', 'pen-line', 'pen-off', 'pen-tool', 'pencil',
    'pencil-line', 'pencil-off', 'pencil-ruler', 'pencil-sparkles', 'pentagon', 'percent', 'person-standing',
    'phi', 'philippine-peso', 'phone', 'phone-call', 'phone-forwarded', 'phone-incoming', 'phone-missed',
    'phone-off', 'phone-outgoing', 'pi', 'piano', 'pickaxe', 'picture-in-picture', 'picture-in-picture-2',
    'piggy-bank', 'pilcrow', 'pilcrow-left', 'pilcrow-right', 'pill', 'pill-bottle', 'pin', 'pin-off',
    'pipette', 'pizza', 'plane', 'plane-landing', 'plane-takeoff', 'plant-pot', 'play', 'play-off',
    'playing-card', 'playing-cards', 'playing-cards-fan', 'plug', 'plug-2', 'plug-zap', 'plus', 'pocket-knife',
    'podium', 'pointer', 'pointer-off', 'popcorn', 'popsicle', 'pound-sterling', 'power', 'power-off',
    'presentation', 'printer', 'printer-check', 'printer-x', 'projector', 'proportions', 'puzzle', 'pyramid',
    'qr-code', 'quote', 'rabbit', 'radar', 'radiation', 'radical', 'radio', 'radio-off', 'radio-receiver',
    'radio-tower', 'radius', 'rainbow', 'rat', 'ratio', 'receipt', 'receipt-cent', 'receipt-euro',
    'receipt-indian-rupee', 'receipt-japanese-yen', 'receipt-pound-sterling', 'receipt-russian-ruble',
    'receipt-swiss-franc', 'receipt-text', 'receipt-turkish-lira', 'rectangle-circle', 'rectangle-ellipsis',
    'rectangle-goggles', 'rectangle-horizontal', 'rectangle-vertical', 'recycle', 'redo', 'redo-2', 'redo-dot',
    'refresh-ccw', 'refresh-ccw-dot', 'refresh-cw', 'refresh-cw-off', 'refrigerator', 'regex',
    'remove-formatting', 'repeat', 'repeat-1', 'repeat-2', 'repeat-off', 'replace', 'replace-all', 'reply',
    'reply-all', 'rewind', 'ribbon', 'road', 'robot-arm', 'robot-vacuum', 'rocket', 'rocking-chair',
    'roller-coaster', 'rose', 'rotate-3d', 'rotate-ccw', 'rotate-ccw-clock', 'rotate-ccw-key',
    'rotate-ccw-square', 'rotate-cw', 'rotate-cw-fading-clock', 'rotate-cw-square', 'route', 'route-off',
    'router', 'rows-2', 'rows-3', 'rows-4', 'rss', 'ruler', 'ruler-dimension-line', 'russian-ruble', 'sailboat',
    'salad', 'sandwich', 'satellite', 'satellite-dish', 'saudi-riyal', 'save', 'save-all', 'save-check',
    'save-off', 'save-pen', 'save-plus', 'scale', 'scale-3d', 'scaling', 'scan', 'scan-barcode', 'scan-box',
    'scan-eye', 'scan-face', 'scan-heart', 'scan-line', 'scan-qr-code', 'scan-search', 'scan-square',
    'scan-text', 'school', 'scissors', 'scissors-line-dashed', 'scooter', 'screen-share', 'screen-share-off',
    'scroll', 'scroll-text', 'search', 'search-alert', 'search-check', 'search-code', 'search-slash',
    'search-x', 'section', 'send', 'send-horizontal', 'send-to-back', 'separator-horizontal',
    'separator-vertical', 'server', 'server-cog', 'server-crash', 'server-off', 'server-plus', 'settings',
    'settings-2', 'shapes', 'share', 'share-2', 'sheet', 'shell', 'shelving-unit', 'shield', 'shield-alert',
    'shield-ban', 'shield-check', 'shield-cog', 'shield-cog-corner', 'shield-ellipsis', 'shield-half',
    'shield-keyhole', 'shield-lock', 'shield-minus', 'shield-off', 'shield-plus', 'shield-question-mark',
    'shield-user', 'shield-x', 'ship', 'ship-cargo', 'ship-wheel', 'shirt', 'shopping-bag', 'shopping-basket',
    'shopping-cart', 'shopping-cart-minus', 'shopping-cart-plus', 'shovel', 'shower-head', 'shredder', 'shrimp',
    'shrimp-off', 'shrink', 'shrub', 'shuffle', 'sigma', 'signal', 'signal-high', 'signal-low', 'signal-medium',
    'signal-zero', 'signature', 'signpost', 'signpost-big', 'siren', 'skip-back', 'skip-forward', 'skull',
    'slash', 'slice', 'sliders-horizontal', 'sliders-vertical', 'smartphone', 'smartphone-charging',
    'smartphone-nfc', 'snail', 'snowflake', 'soap-dispenser-droplet', 'sofa', 'solar-panel', 'soup', 'space',
    'spade', 'sparkle', 'sparkles', 'speaker', 'speech', 'spell-check', 'spell-check-2', 'spline',
    'spline-pointer', 'split', 'spool', 'sport-shoe', 'spotlight', 'spray-can', 'sprout', 'square',
    'square-activity', 'square-arrow-down', 'square-arrow-down-left', 'square-arrow-down-right',
    'square-arrow-left', 'square-arrow-out-down-left', 'square-arrow-out-down-right',
    'square-arrow-out-up-left', 'square-arrow-out-up-right', 'square-arrow-right', 'square-arrow-right-enter',
    'square-arrow-right-exit', 'square-arrow-up', 'square-arrow-up-left', 'square-arrow-up-right',
    'square-asterisk', 'square-bookmark', 'square-bottom-dashed-scissors',
    'square-centerline-dashed-horizontal', 'square-centerline-dashed-vertical', 'square-chart-gantt',
    'square-check', 'square-check-big', 'square-chevron-down', 'square-chevron-left', 'square-chevron-right',
    'square-chevron-up', 'square-code', 'square-dashed', 'square-dashed-bottom', 'square-dashed-bottom-code',
    'square-dashed-kanban', 'square-dashed-mouse-pointer', 'square-dashed-text', 'square-dashed-top-solid',
    'square-dimensions', 'square-divide', 'square-dot', 'square-equal', 'square-exclamation-point',
    'square-function', 'square-kanban', 'square-library', 'square-m', 'square-menu', 'square-minus',
    'square-mouse-pointer', 'square-off', 'square-parking', 'square-parking-off', 'square-pause', 'square-pen',
    'square-percent', 'square-pi', 'square-pilcrow', 'square-play', 'square-plus', 'square-power',
    'square-radical', 'square-round-corner', 'square-scissors', 'square-sigma', 'square-slash',
    'square-split-horizontal', 'square-split-vertical', 'square-square', 'square-stack', 'square-star',
    'square-stop', 'square-terminal', 'square-text', 'square-user', 'square-user-round', 'square-x',
    'squares-exclude', 'squares-intersect', 'squares-subtract', 'squares-unite', 'squircle', 'squircle-dashed',
    'squirrel', 'stamp', 'star', 'star-check', 'star-half', 'star-minus', 'star-off', 'star-plus', 'star-x',
    'step-back', 'step-forward', 'stethoscope', 'sticker', 'sticky-note', 'sticky-note-check',
    'sticky-note-minus', 'sticky-note-off', 'sticky-note-plus', 'sticky-note-x', 'sticky-notes', 'stone',
    'store', 'stretch-horizontal', 'stretch-vertical', 'strikethrough', 'subscript', 'summary', 'sun',
    'sun-dim', 'sun-medium', 'sun-moon', 'sun-snow', 'sunrise', 'sunset', 'superscript', 'swatch-book',
    'swiss-franc', 'switch-camera', 'sword', 'swords', 'syringe', 'table', 'table-2', 'table-cells-merge',
    'table-cells-split', 'table-columns-split', 'table-of-contents', 'table-properties', 'table-rows-split',
    'tablet', 'tablet-smartphone', 'tablets', 'tag', 'tag-plus', 'tag-x', 'tags', 'tally-1', 'tally-2',
    'tally-3', 'tally-4', 'tally-5', 'tangent', 'target', 'telescope', 'tent', 'tent-tree', 'terminal',
    'test-tube', 'test-tube-diagonal', 'test-tubes', 'text-align-center', 'text-align-end',
    'text-align-justify', 'text-align-start', 'text-cursor', 'text-cursor-input', 'text-initial', 'text-quote',
    'text-search', 'text-wrap', 'theater', 'thermometer', 'thermometer-snowflake', 'thermometer-sun',
    'thumbs-down', 'thumbs-up', 'tic-tac-toe', 'ticket', 'ticket-check', 'ticket-minus', 'ticket-percent',
    'ticket-plus', 'ticket-slash', 'ticket-x', 'tickets', 'tickets-plane', 'timeline', 'timer', 'timer-off',
    'timer-reset', 'toggle-left', 'toggle-right', 'toilet', 'tool-case', 'toolbox', 'toothbrush',
    'toothbrush-sparkles', 'tornado', 'torus', 'touchpad', 'touchpad-off', 'towel-rack', 'tower-control',
    'toy-brick', 'tractor', 'traffic-cone', 'trailer', 'train-front', 'train-front-tunnel', 'train-track',
    'tram-front', 'transgender', 'trash', 'trash-off', 'tree-deciduous', 'tree-palm', 'tree-pine', 'trees',
    'trending-down', 'trending-up', 'trending-up-down', 'triangle', 'triangle-alert', 'triangle-dashed',
    'triangle-right', 'triangles-centerline-dashed-horizontal', 'triangles-centerline-dashed-vertical',
    'trophy', 'truck', 'truck-electric', 'turkish-lira', 'turntable', 'turtle', 'tv', 'tv-minimal',
    'tv-minimal-play', 'type', 'type-outline', 'umbrella', 'umbrella-off', 'underline', 'undo', 'undo-2',
    'undo-dot', 'unfold-horizontal', 'unfold-vertical', 'ungroup', 'university', 'unlink', 'unlink-2', 'unplug',
    'upload', 'usb', 'usb-c-port', 'user', 'user-check', 'user-cog', 'user-group', 'user-key', 'user-lock',
    'user-minus', 'user-pen', 'user-plus', 'user-round', 'user-round-arrow-left', 'user-round-check',
    'user-round-cog', 'user-round-group', 'user-round-key', 'user-round-minus', 'user-round-pen',
    'user-round-plus', 'user-round-search', 'user-round-x', 'user-search', 'user-shield', 'user-star', 'user-x',
    'users', 'users-round', 'utensils', 'utensils-crossed', 'utility-pole', 'van', 'variable', 'vault',
    'vector-polygon', 'vector-square', 'vegan', 'venetian-mask', 'venus', 'venus-and-mars', 'vibrate',
    'vibrate-off', 'video', 'video-off', 'videotape', 'view', 'virus', 'virus-off', 'voicemail', 'volleyball',
    'volume', 'volume-1', 'volume-2', 'volume-off', 'volume-x', 'vote', 'wallet', 'wallet-cards',
    'wallet-minimal', 'wallpaper', 'wand', 'wand-sparkles', 'warehouse', 'washing-machine', 'watch',
    'waves-arrow-down', 'waves-arrow-up', 'waves-horizontal', 'waves-ladder', 'waves-vertical', 'waypoints',
    'webcam', 'webcam-off', 'webhook', 'webhook-off', 'weight', 'weight-tilde', 'wheat', 'wheat-off', 'whistle',
    'whole-word', 'wifi', 'wifi-cog', 'wifi-high', 'wifi-low', 'wifi-off', 'wifi-pen', 'wifi-sync', 'wifi-zero',
    'wind', 'wind-arrow-down', 'wine', 'wine-off', 'workflow', 'worm', 'wrench', 'wrench-off', 'x',
    'x-line-top', 'zap', 'zap-off', 'zodiac-aquarius', 'zodiac-aries', 'zodiac-cancer', 'zodiac-capricorn',
    'zodiac-gemini', 'zodiac-leo', 'zodiac-libra', 'zodiac-ophiuchus', 'zodiac-pisces', 'zodiac-sagittarius',
    'zodiac-scorpio', 'zodiac-taurus', 'zodiac-virgo', 'zoom-in', 'zoom-out'
];

/* Los de uso comun en el ERP: salen primero cuando el buscador esta vacio. */
window.CS_ICONS_SUGERIDOS = [
    'layout-grid', 'users', 'user-round', 'users-round', 'user-plus', 'user-cog', 'contact', 'id-card',
    'calculator', 'wallet', 'banknote', 'coins', 'hand-coins', 'piggy-bank', 'receipt', 'credit-card',
    'landmark', 'chart-column', 'chart-bar', 'chart-pie', 'chart-line', 'trending-up', 'chef-hat', 'utensils',
    'coffee', 'factory', 'warehouse', 'package', 'boxes', 'truck', 'shopping-cart', 'store', 'briefcase',
    'badge-check', 'clipboard-check', 'clipboard-list', 'list-checks', 'list-tree', 'file-text', 'files',
    'folder-open', 'folder-tree', 'archive', 'inbox', 'mail', 'bell', 'megaphone', 'calendar-days',
    'calendar-range', 'calendar-check', 'calendar-x', 'clock', 'timer', 'key-round', 'shield', 'lock',
    'settings', 'sliders-horizontal', 'terminal', 'sparkles', 'bot', 'database', 'table-2', 'grid-3x3',
    'layers', 'tag', 'tags', 'scale', 'percent', 'heart-handshake', 'graduation-cap', 'book-open', 'map-pin',
    'globe', 'phone', 'printer', 'qr-code', 'scan-line', 'search', 'refresh-cw', 'wrench', 'hammer', 'flame',
    'leaf', 'activity', 'gauge', 'target', 'award', 'star', 'flag', 'pin', 'house', 'image', 'camera', 'video',
    'mic', 'headphones', 'palette', 'paintbrush', 'pen-line', 'notebook-pen', 'file-spreadsheet', 'file-check',
    'file-plus', 'folder-plus', 'info', 'triangle-alert', 'check', 'x', 'plus', 'minus', 'link', 'share-2',
    'send', 'download', 'upload', 'cloud', 'server', 'cpu', 'monitor', 'smartphone', 'tablet', 'wifi',
    'bluetooth', 'battery', 'plug', 'zap', 'sun', 'moon', 'umbrella', 'thermometer', 'droplet', 'wind',
    'recycle', 'shopping-bag', 'ticket', 'gift', 'trophy', 'medal', 'crown', 'rocket', 'plane', 'car', 'bus',
    'bike', 'ship', 'train-front', 'fuel', 'construction', 'hard-hat', 'ruler', 'pencil-ruler', 'compass',
    'map', 'route', 'navigation', 'signpost', 'milestone', 'footprints', 'baby', 'stethoscope', 'pill',
    'syringe', 'ambulance', 'hospital', 'cross', 'shirt', 'glasses', 'watch', 'gem', 'wallet-cards', 'vault',
    'banknote-arrow-up', 'receipt-text', 'scroll-text', 'stamp', 'scan-face', 'user-check', 'user-x',
    'handshake', 'building', 'school', 'library', 'church', 'tent', 'mountain', 'trees', 'sprout', 'wheat',
    'beef', 'egg', 'fish', 'pizza', 'cake', 'wine', 'beer', 'cup-soda', 'ice-cream-cone', 'soup', 'sandwich',
    'salad', 'drumstick', 'croissant', 'cookie', 'candy', 'apple', 'cherry', 'citrus', 'carrot', 'milk'
];

window.CS_ICONS_ES = {
    usuario: ['user'],
    usuarios: ['users'],
    persona: ['user', 'person'],
    gente: ['users'],
    equipo: ['users', 'team'],
    colaborador: ['user', 'contact', 'id-card'],
    empleado: ['user', 'id-card', 'briefcase'],
    cliente: ['user', 'handshake', 'store'],
    contacto: ['contact', 'phone', 'mail'],
    perfil: ['user', 'id-card'],
    rol: ['shield', 'key', 'users'],
    dinero: ['coins', 'banknote', 'wallet', 'dollar', 'hand-coins'],
    efectivo: ['banknote', 'coins'],
    pago: ['credit-card', 'banknote', 'hand-coins', 'receipt'],
    caja: ['wallet', 'vault', 'banknote', 'box'],
    banco: ['landmark', 'banknote', 'piggy'],
    moneda: ['coins', 'coin', 'dollar', 'euro'],
    cartera: ['wallet'],
    factura: ['receipt', 'file-text', 'scroll-text'],
    recibo: ['receipt'],
    ticket: ['ticket', 'receipt'],
    contabilidad: ['calculator', 'receipt', 'landmark', 'book'],
    calculadora: ['calculator'],
    impuesto: ['percent', 'receipt'],
    porcentaje: ['percent'],
    precio: ['tag', 'dollar', 'badge-dollar'],
    descuento: ['percent', 'tag', 'badge-percent'],
    presupuesto: ['piggy', 'wallet', 'chart'],
    ahorro: ['piggy'],
    prestamo: ['hand-coins', 'piggy', 'landmark'],
    nomina: ['banknote', 'wallet', 'hand-coins'],
    tesoreria: ['wallet', 'landmark', 'vault', 'banknote'],
    credito: ['credit-card'],
    tarjeta: ['credit-card', 'id-card', 'wallet-cards'],
    grafica: ['chart'],
    grafico: ['chart'],
    estadistica: ['chart', 'trending'],
    reporte: ['chart', 'file-text', 'clipboard'],
    indicador: ['gauge', 'chart', 'trending', 'activity'],
    tendencia: ['trending'],
    meta: ['target', 'goal', 'flag'],
    objetivo: ['target', 'crosshair', 'goal'],
    calendario: ['calendar'],
    fecha: ['calendar'],
    dia: ['calendar', 'sun'],
    mes: ['calendar'],
    hora: ['clock', 'timer', 'alarm'],
    reloj: ['clock', 'watch', 'timer'],
    tiempo: ['clock', 'timer', 'hourglass'],
    turno: ['clock', 'calendar', 'alarm'],
    vacaciones: ['palmtree', 'sun', 'plane', 'calendar'],
    permiso: ['key', 'shield', 'lock', 'calendar'],
    incidencia: ['calendar-x', 'alert', 'triangle-alert'],
    alerta: ['alert', 'bell', 'siren'],
    aviso: ['bell', 'megaphone', 'info'],
    notificacion: ['bell'],
    anuncio: ['megaphone', 'speaker'],
    campana: ['bell'],
    mensaje: ['message', 'mail', 'send'],
    correo: ['mail', 'inbox', 'send'],
    chat: ['message'],
    bandeja: ['inbox', 'archive'],
    buzon: ['inbox', 'mailbox'],
    telefono: ['phone', 'smartphone'],
    celular: ['smartphone'],
    archivo: ['file', 'folder', 'archive'],
    documento: ['file', 'scroll', 'notebook'],
    carpeta: ['folder'],
    expediente: ['folder', 'file', 'files'],
    hoja: ['file', 'sheet', 'leaf'],
    excel: ['file-spreadsheet', 'sheet', 'table'],
    tabla: ['table', 'grid', 'sheet'],
    lista: ['list'],
    formulario: ['clipboard', 'file-pen', 'form'],
    firma: ['pen', 'signature', 'file-pen'],
    lapiz: ['pencil', 'pen'],
    pluma: ['pen', 'feather'],
    nota: ['sticky-note', 'notebook', 'notepad'],
    libro: ['book'],
    biblioteca: ['library', 'book'],
    manual: ['book', 'notebook'],
    conocimiento: ['brain', 'book', 'lightbulb', 'graduation'],
    escuela: ['school', 'graduation', 'book'],
    curso: ['graduation', 'book', 'presentation'],
    capacitacion: ['graduation', 'presentation', 'book'],
    examen: ['clipboard', 'file-check', 'graduation'],
    encuesta: ['clipboard-list', 'vote', 'list-checks', 'message-square'],
    pregunta: ['question', 'help'],
    ayuda: ['help', 'life-buoy', 'question', 'info'],
    informacion: ['info'],
    configuracion: ['settings', 'sliders', 'wrench', 'cog'],
    ajustes: ['settings', 'sliders', 'cog'],
    herramienta: ['wrench', 'hammer', 'tool'],
    mantenimiento: ['wrench', 'hammer', 'hard-hat', 'construction'],
    seguridad: ['shield', 'lock', 'key'],
    candado: ['lock'],
    llave: ['key'],
    clave: ['key', 'lock', 'asterisk'],
    contrasena: ['key', 'lock', 'asterisk'],
    permisos: ['key', 'shield', 'lock'],
    escudo: ['shield'],
    acceso: ['key', 'door', 'log-in', 'fingerprint'],
    huella: ['fingerprint'],
    entrada: ['log-in', 'door-open', 'arrow-right'],
    salida: ['log-out', 'door-closed', 'arrow-left'],
    puerta: ['door'],
    casa: ['house', 'home'],
    inicio: ['house', 'home'],
    edificio: ['building'],
    empresa: ['building', 'briefcase', 'landmark'],
    sucursal: ['store', 'building', 'map-pin'],
    tienda: ['store', 'shopping'],
    oficina: ['building', 'briefcase'],
    almacen: ['warehouse', 'package', 'boxes', 'archive'],
    bodega: ['warehouse', 'boxes'],
    inventario: ['package', 'boxes', 'clipboard', 'scan'],
    producto: ['package', 'box', 'tag'],
    articulo: ['package', 'box', 'tag'],
    paquete: ['package'],
    envio: ['truck', 'send', 'package'],
    entrega: ['truck', 'package-check', 'hand'],
    camion: ['truck'],
    transporte: ['truck', 'bus', 'car', 'ship'],
    ruta: ['route', 'map', 'navigation'],
    mapa: ['map'],
    ubicacion: ['map-pin', 'locate', 'navigation'],
    direccion: ['map-pin', 'signpost', 'compass'],
    mundo: ['globe', 'earth'],
    viaje: ['plane', 'luggage', 'map'],
    compra: ['shopping', 'cart', 'bag', 'receipt'],
    carrito: ['shopping-cart', 'cart'],
    venta: ['shopping', 'tag', 'dollar', 'store', 'badge-dollar'],
    pedido: ['clipboard-list', 'package', 'shopping'],
    orden: ['clipboard-list', 'list-ordered', 'receipt'],
    cotizacion: ['file-text', 'receipt', 'calculator'],
    proveedor: ['truck', 'handshake', 'store'],
    contrato: ['file-signature', 'file-pen', 'handshake', 'scroll'],
    acuerdo: ['handshake'],
    comida: ['utensils', 'chef-hat', 'pizza', 'soup', 'sandwich'],
    cocina: ['chef-hat', 'cooking-pot', 'utensils', 'microwave', 'refrigerator'],
    receta: ['chef-hat', 'cooking-pot', 'notebook', 'scroll-text'],
    restaurante: ['utensils', 'chef-hat', 'concierge-bell'],
    cafe: ['coffee', 'cup-soda'],
    bebida: ['cup-soda', 'wine', 'beer', 'coffee', 'glass-water'],
    pan: ['croissant', 'wheat', 'cake'],
    panaderia: ['croissant', 'wheat', 'cake'],
    pastel: ['cake'],
    ingrediente: ['wheat', 'egg', 'carrot', 'beef', 'salt'],
    costo: ['calculator', 'dollar', 'receipt', 'scale'],
    balanza: ['scale'],
    peso: ['scale', 'weight', 'dumbbell'],
    medida: ['ruler', 'scale', 'gauge'],
    produccion: ['factory', 'cog', 'package', 'conveyor'],
    fabrica: ['factory'],
    maquina: ['cog', 'factory', 'cpu'],
    calidad: ['badge-check', 'shield-check', 'clipboard-check', 'award', 'star'],
    revision: ['clipboard-check', 'search-check', 'eye', 'file-check'],
    inspeccion: ['search', 'eye', 'scan', 'clipboard-check'],
    auditoria: ['clipboard-check', 'file-check', 'search', 'scale'],
    aprobado: ['check', 'badge-check', 'circle-check', 'thumbs-up'],
    rechazado: ['x', 'circle-x', 'ban', 'thumbs-down'],
    pendiente: ['clock', 'hourglass', 'circle-dashed'],
    estado: ['activity', 'circle', 'badge'],
    activo: ['toggle-right', 'check', 'power'],
    inactivo: ['toggle-left', 'ban', 'power-off'],
    buscar: ['search', 'scan', 'zoom'],
    lupa: ['search', 'zoom'],
    filtro: ['filter', 'funnel'],
    ordenar: ['arrow-up-down', 'sort', 'list-ordered'],
    editar: ['pencil', 'pen', 'edit', 'square-pen'],
    borrar: ['trash', 'eraser', 'x'],
    eliminar: ['trash', 'x', 'ban'],
    agregar: ['plus'],
    nuevo: ['plus', 'sparkles', 'file-plus'],
    guardar: ['save', 'hard-drive', 'download'],
    descargar: ['download', 'cloud-download'],
    subir: ['upload', 'cloud-upload', 'arrow-up'],
    compartir: ['share', 'send', 'link'],
    enlace: ['link', 'external-link'],
    imprimir: ['printer'],
    impresora: ['printer'],
    escaner: ['scan', 'scan-line', 'qr-code'],
    codigo: ['code', 'qr-code', 'barcode', 'terminal'],
    barras: ['barcode', 'chart-bar'],
    qr: ['qr-code'],
    imagen: ['image', 'camera', 'picture'],
    foto: ['camera', 'image'],
    video: ['video', 'film', 'clapperboard'],
    audio: ['mic', 'volume', 'headphones', 'music'],
    musica: ['music', 'headphones'],
    computadora: ['monitor', 'laptop', 'pc-case', 'computer'],
    sistema: ['cpu', 'server', 'terminal', 'settings'],
    servidor: ['server', 'database', 'hard-drive'],
    datos: ['database', 'table', 'chart', 'hard-drive'],
    nube: ['cloud'],
    red: ['network', 'wifi', 'share', 'globe', 'cable'],
    internet: ['globe', 'wifi', 'cloud'],
    programacion: ['code', 'terminal', 'braces', 'bug'],
    desarrollo: ['code', 'terminal', 'git', 'bug', 'wrench'],
    error: ['bug', 'triangle-alert', 'circle-x', 'octagon-alert'],
    robot: ['bot', 'brain-circuit', 'cpu'],
    inteligencia: ['brain', 'sparkles', 'bot'],
    ia: ['brain', 'sparkles', 'bot', 'wand'],
    magia: ['sparkles', 'wand'],
    estrella: ['star', 'sparkle'],
    favorito: ['star', 'heart', 'bookmark'],
    corazon: ['heart'],
    salud: ['heart-pulse', 'stethoscope', 'activity', 'cross', 'hospital'],
    medico: ['stethoscope', 'hospital', 'pill', 'syringe', 'briefcase-medical'],
    hospital: ['hospital', 'cross', 'ambulance'],
    medicina: ['pill', 'syringe', 'stethoscope'],
    seguro: ['shield', 'umbrella', 'life-buoy'],
    premio: ['award', 'trophy', 'medal', 'gift', 'crown'],
    trofeo: ['trophy'],
    logro: ['award', 'medal', 'trophy', 'party-popper'],
    regalo: ['gift', 'party-popper'],
    fiesta: ['party-popper', 'cake', 'gift'],
    bandera: ['flag'],
    pin: ['pin', 'map-pin', 'bookmark'],
    marcador: ['bookmark', 'flag', 'pin'],
    etiqueta: ['tag', 'tags', 'bookmark'],
    categoria: ['tag', 'tags', 'folder', 'layers', 'shapes'],
    modulo: ['layout-grid', 'boxes', 'blocks', 'grid', 'component'],
    seccion: ['file-text', 'panel', 'layout', 'columns'],
    menu: ['menu', 'list', 'panel-left', 'layout'],
    panel: ['panel', 'layout', 'dashboard', 'gauge'],
    tablero: ['layout-dashboard', 'gauge', 'kanban', 'clipboard'],
    capas: ['layers'],
    cuadricula: ['grid', 'layout-grid'],
    arbol: ['list-tree', 'folder-tree', 'tree', 'network', 'git-branch'],
    jerarquia: ['network', 'list-tree', 'folder-tree', 'git-branch'],
    flujo: ['workflow', 'git-branch', 'route', 'arrow-right', 'waypoints'],
    proceso: ['workflow', 'cog', 'refresh', 'route', 'list-checks'],
    tarea: ['list-checks', 'check-square', 'square-check', 'clipboard-check', 'list-todo'],
    actividad: ['activity', 'list-checks', 'calendar-check'],
    proyecto: ['folder-kanban', 'kanban', 'briefcase', 'layout-list'],
    asunto: ['list-checks', 'message-circle', 'file-text', 'clipboard'],
    recordatorio: ['bell', 'alarm', 'calendar-clock', 'sticky-note'],
    historial: ['history', 'clock', 'scroll', 'archive'],
    version: ['git-branch', 'history', 'tag', 'package'],
    respaldo: ['database-backup', 'archive', 'hard-drive', 'save'],
    sincronizar: ['refresh', 'rotate', 'repeat', 'cloud'],
    actualizar: ['refresh', 'rotate', 'arrow-up-circle'],
    cargar: ['loader', 'upload', 'refresh'],
    cerrar: ['x', 'log-out', 'door-closed'],
    abrir: ['folder-open', 'door-open', 'external-link', 'lock-open'],
    ver: ['eye', 'view', 'scan-eye'],
    ocultar: ['eye-off'],
    visible: ['eye'],
    oculto: ['eye-off', 'ghost'],
    bloquear: ['lock', 'ban', 'shield-ban'],
    desbloquear: ['lock-open', 'unlock', 'key'],
    apagar: ['power', 'power-off'],
    encender: ['power', 'zap', 'lightbulb'],
    luz: ['lightbulb', 'sun', 'lamp', 'zap'],
    idea: ['lightbulb', 'brain', 'sparkles'],
    energia: ['zap', 'battery', 'plug', 'flame', 'bolt'],
    fuego: ['flame'],
    agua: ['droplet', 'waves', 'glass-water'],
    clima: ['cloud', 'sun', 'cloud-rain', 'thermometer', 'wind'],
    temperatura: ['thermometer'],
    planta: ['sprout', 'leaf', 'flower', 'trees'],
    naturaleza: ['leaf', 'trees', 'mountain', 'sprout', 'flower'],
    reciclar: ['recycle'],
    limpieza: ['spray-can', 'brush', 'paintbrush', 'sparkles', 'wind'],
    ropa: ['shirt'],
    uniforme: ['shirt', 'hard-hat'],
    casco: ['hard-hat'],
    construccion: ['construction', 'hard-hat', 'hammer', 'brick-wall'],
    diseno: ['palette', 'paintbrush', 'pen-tool', 'figma', 'layout'],
    tema: ['palette', 'paintbrush', 'sun-moon', 'swatch-book'],
    color: ['palette', 'paintbrush', 'pipette', 'swatch'],
    marketing: ['megaphone', 'target', 'trending-up', 'share'],
    publicidad: ['megaphone', 'presentation', 'badge-percent'],
    redes: ['share-2', 'at-sign', 'hash', 'globe', 'thumbs-up'],
    evento: ['calendar', 'party-popper', 'ticket', 'megaphone'],
    boleto: ['ticket'],
    hotel: ['hotel', 'bed', 'concierge-bell'],
    cama: ['bed'],
    habitacion: ['bed', 'door', 'hotel'],
    juego: ['gamepad', 'dice', 'puzzle', 'joystick'],
    deporte: ['dumbbell', 'trophy', 'bike', 'volleyball', 'medal'],
    avion: ['plane'],
    coche: ['car'],
    carro: ['car', 'shopping-cart'],
    barco: ['ship', 'sailboat', 'anchor'],
    tren: ['train', 'tram'],
    bici: ['bike'],
    gasolina: ['fuel'],
    estacionamiento: ['car', 'parking', 'circle-parking', 'square-parking'],
    bebe: ['baby'],
    mascota: ['dog', 'cat', 'paw-print'],
    animal: ['dog', 'cat', 'bird', 'fish', 'paw-print', 'rabbit'],
    mujer: ['user', 'venus'],
    hombre: ['user', 'mars'],
    genero: ['venus', 'mars', 'transgender'],
    accesibilidad: ['accessibility', 'person-standing', 'ear'],
    discapacidad: ['accessibility'],
    mano: ['hand', 'grab', 'pointer'],
    pulgar: ['thumbs-up', 'thumbs-down'],
    ojo: ['eye'],
    boca: ['smile', 'laugh', 'frown'],
    cara: ['smile', 'user', 'scan-face', 'laugh', 'meh'],
    feliz: ['smile', 'laugh', 'party-popper'],
    triste: ['frown'],
    voto: ['vote'],
    ley: ['scale', 'gavel', 'landmark', 'scroll'],
    legal: ['scale', 'gavel', 'file-signature', 'stamp'],
    sello: ['stamp', 'badge', 'award'],
    certificado: ['award', 'badge-check', 'scroll-text', 'file-badge'],
    diploma: ['scroll-text', 'graduation-cap', 'award'],
    credencial: ['id-card', 'badge', 'contact', 'scan-face'],
    gafete: ['id-card', 'badge', 'contact'],
    puesto: ['briefcase', 'id-card', 'user-cog', 'badge'],
    departamento: ['building', 'network', 'users', 'layout-grid'],
    area: ['layout', 'square', 'map', 'building'],
    organigrama: ['network', 'git-fork', 'list-tree', 'workflow'],
    reclutamiento: ['user-search', 'user-plus', 'briefcase'],
    candidato: ['user-search', 'user-plus', 'contact'],
    vacante: ['user-plus', 'briefcase', 'user-search'],
    baja: ['user-minus', 'user-x', 'arrow-down', 'trending-down', 'log-out'],
    alta: ['user-plus', 'plus', 'arrow-up', 'trending-up'],
    rotacion: ['refresh', 'rotate', 'repeat', 'users'],
    asistencia: ['calendar-check', 'user-check', 'clipboard-check', 'clock'],
    retardo: ['clock-alert', 'alarm-clock', 'timer', 'hourglass'],
    falta: ['user-x', 'calendar-x', 'circle-x'],
    horario: ['clock', 'calendar-clock', 'timer'],
    jornada: ['clock', 'sun', 'calendar-days'],
    valores: ['heart-handshake', 'gem', 'star', 'award', 'sparkles'],
    cultura: ['heart-handshake', 'users', 'sparkles', 'palette'],
    bienestar: ['heart', 'heart-pulse', 'smile', 'leaf'],
    comunicacion: ['megaphone', 'message', 'mail', 'radio', 'rss'],
    radio: ['radio', 'antenna', 'podcast'],
    television: ['tv', 'monitor'],
    pantalla: ['monitor', 'tv', 'tablet', 'smartphone', 'screen'],
    teclado: ['keyboard'],
    raton: ['mouse'],
    ventana: ['app-window', 'panel-top', 'square'],
    cursor: ['mouse-pointer', 'pointer'],
    mover: ['move', 'grip', 'arrow'],
    arrastrar: ['grip', 'move', 'hand'],
    flecha: ['arrow'],
    arriba: ['arrow-up', 'chevron-up', 'move-up'],
    abajo: ['arrow-down', 'chevron-down', 'move-down'],
    izquierda: ['arrow-left', 'chevron-left'],
    derecha: ['arrow-right', 'chevron-right'],
    expandir: ['expand', 'maximize', 'chevrons', 'unfold'],
    contraer: ['shrink', 'minimize', 'fold'],
    circulo: ['circle'],
    cuadro: ['square'],
    triangulo: ['triangle'],
    forma: ['shapes', 'square', 'circle', 'triangle', 'hexagon'],
    texto: ['text', 'type', 'case', 'letter'],
    letra: ['type', 'case', 'a-large-small', 'text'],
    numero: ['hash', 'binary', 'calculator', 'sigma'],
    suma: ['plus', 'sigma', 'calculator'],
    resta: ['minus', 'calculator'],
    multiplicar: ['x', 'asterisk', 'calculator'],
    dividir: ['divide', 'calculator', 'split'],
    igual: ['equal'],
    matematicas: ['calculator', 'sigma', 'pi', 'divide', 'radical'],
    regla: ['ruler', 'pencil-ruler', 'scale'],
    compas: ['compass', 'drafting-compass'],
    engrane: ['cog', 'settings'],
    tuerca: ['nut', 'cog', 'wrench'],
    martillo: ['hammer', 'gavel'],
    bombilla: ['lightbulb'],
    enchufe: ['plug', 'plug-zap', 'cable'],
    bateria: ['battery'],
    senal: ['signal', 'wifi', 'antenna', 'radio-tower'],
    antena: ['antenna', 'radio-tower', 'satellite'],
    satelite: ['satellite'],
    cohete: ['rocket'],
    espacio: ['rocket', 'orbit', 'moon', 'sparkles', 'telescope'],
    luna: ['moon'],
    sol: ['sun'],
    planeta: ['earth', 'globe', 'orbit']
};
