-- Carga Insumos Reginas -> fayxzvov_inventory (companies_id=1, branch_id=1, warehouse=1)
USE fayxzvov_inventory;
SET FOREIGN_KEY_CHECKS=0;
DELETE FROM item_attribute;
DELETE FROM item;
DELETE FROM item_category;
ALTER TABLE item_attribute AUTO_INCREMENT=1;
ALTER TABLE item AUTO_INCREMENT=1;
ALTER TABLE item_category AUTO_INCREMENT=1;
SET FOREIGN_KEY_CHECKS=1;

-- Categorias (ubicaciones del Excel)
INSERT INTO item_category (name, companies_id, warehouse_id, active) VALUES ('ANAQUEL 1', 1, 1, 1);
INSERT INTO item_category (name, companies_id, warehouse_id, active) VALUES ('ANAQUEL 2', 1, 1, 1);
INSERT INTO item_category (name, companies_id, warehouse_id, active) VALUES ('ANAQUEL 3', 1, 1, 1);
INSERT INTO item_category (name, companies_id, warehouse_id, active) VALUES ('REFRIGERADOR', 1, 1, 1);
INSERT INTO item_category (name, companies_id, warehouse_id, active) VALUES ('CONGELADOR', 1, 1, 1);
INSERT INTO item_category (name, companies_id, warehouse_id, active) VALUES ('ANAQUEL 4', 1, 1, 1);

-- Unidades (presentaciones) faltantes
INSERT INTO unit (name, code, companies_id, active) SELECT '2 KG','2 KG',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='2 KG' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT '25 KG','25 KG',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='25 KG' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT '2KG','2KG',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='2KG' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT '3.5 KG','3.5 KG',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='3.5 KG' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT '4 LT','4 LT',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='4 LT' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT '500 GR','500 GR',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='500 GR' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT '5KG','5KG',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='5KG' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'BOLSA','BOLSA',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='BOLSA' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'BOTE','BOTE',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='BOTE' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'BOTELLA','BOTELLA',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='BOTELLA' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'CAJA','CAJA',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='CAJA' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'CAJITA','CAJITA',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='CAJITA' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'CJA 360','CJA 360',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='CJA 360' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'FRASCO','FRASCO',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='FRASCO' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'KILO','KILO',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='KILO' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'LATA','LATA',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='LATA' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'LITRO','LITRO',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='LITRO' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'PAQUETE','PAQUETE',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='PAQUETE' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'PZ','PZ',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='PZ' AND companies_id=1);
INSERT INTO unit (name, code, companies_id, active) SELECT 'ROLLO','ROLLO',1,1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM unit WHERE name='ROLLO' AND companies_id=1);

-- Items + atributos
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('FECULA DE MAIZ', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('POLVO PARA HORNEAR', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CANELA EN POLVO', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GLASSE DE FRESA', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MANGA DE PIÑA', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MANGA DE FRESA', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MANGA DE ZARZAMORA', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GANASHE BLANCO', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GANASHE OSCURO', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MANGA DE VAINILLA', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CHOCOLATE CARAT', (SELECT id FROM item_category WHERE name='ANAQUEL 1' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('COCOA', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('NUEZ PICADA', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('AJONJOLI', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('ALMENDRA FILETEADA', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('COCO', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CACAHUATE', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GALLETA MARIAS', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='ROLLO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('LECHE PRADEL', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('JARABE 3 LECHES', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('AMBIANTE', (SELECT id FROM item_category WHERE name='ANAQUEL 2' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GALLETA RITZ', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='ROLLO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GALLETA OREO', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PAQUETE' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GALLETA LOTUS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PAQUETE' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MIEL', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTE' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BOTE DE CANELA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTE' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CREMA LOTUS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTE' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('HARINA DE ALMENDRAS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('TEQUILA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTELLA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('ROMPOPE', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTELLA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BRANDY', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTELLA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('LICOR DE BAILEYS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTELLA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('OSTIONES AHUMADOS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJITA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MERMELADA DE FRESA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='FRASCO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MERMELADA DE ZARZAMORA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='FRASCO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CREMA DE AVELLANAS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='FRASCO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('EXTRACTO DE VAINILLA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('LECHE LALA DESLACTOSADA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DULCE DE LECHE', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LATA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('LECHERA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LATA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CARNETION', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LATA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('LEVADURA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CHOCOLATE PARA DONA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('COBERTURA PARA DONA MAPLE', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GELATINAS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MEJORAMIX', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOLSA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('SALSA PARA PIZZA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOLSA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CAFE', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOTE' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MAYONESA MEMBER`S MARK', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='3.5 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MAYONESA MCCORMICK', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='3.5 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('SAL', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('ACEITE', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('VAINILLA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='4 LT' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CEREZAS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='3.5 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DURAZNO MITADES', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='3.5 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('PIÑA TROZOS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='3.5 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('PIÑA RODAJAS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='3.5 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GRANILLO DE COLORES', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='BOLSA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('AZUCAR REFINADA', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('AZUCAR MASCABADO', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('AZUCAR GLASS', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('AZUCAR ESTANDAR', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='25 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('HARINA MAYRAN', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='25 KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('HUEVO', (SELECT id FROM item_category WHERE name='ANAQUEL 3' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CJA 360' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MANTEQUILLA AZTURIAS', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MARGARINA BIZCOCHO', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('FEITE DANES', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CAJETA', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('SELECTA', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('QUESO CREMA SANTA CRUZ', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('QUESO PHILADELPHIA', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CHOCOLATE BLANCO', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='500 GR' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('YOGURT', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='LITRO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('FERREROS', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CREMA DE BAILYES', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('GRANILLO DE CHOCOLATE', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('JAMON', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('SALCHICHA', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('QUESO AMARILLO', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('QUESO MOZZARELLA', (SELECT id FROM item_category WHERE name='REFRIGERADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CREMA PARA BATIR BETTERCREAM', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOBLE CHOCOLATE', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('JARABE 3 LECHES RICHES', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('JARABE DE BAILYES', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('FRUTOS ROJOS CONGELADOS', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('FRESAS CONGELADAS', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('MANGO EN CUBITOS', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('PULPA DE MANGO', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='KILO' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('PEPERONI', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('ELOTE EN GRANO', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CHOCOLANTE OSCURO', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='5KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CHOCOLANTE LECHE', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='5KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('RAJAS', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='2KG' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('QUESO DOBLE CREMA', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CHISPA DE CHOCOLATE', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CONCENTRADO DE JARABE 3 LECHES', (SELECT id FROM item_category WHERE name='CONGELADOR' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='CAJA' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO C-85', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO C-95', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO C-105', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO P-32AN', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO P-20AN', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO C-15N', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO REBANADAS', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO LASAÑA', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO 1/4 DE PLANCHA', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO 1/2 PLANCHA', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO CUPCAKE', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO BOCADILLO GD', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO BOCADILLO CH', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO ROSCA MED', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO ROSCA GD', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO ROSCA FAMILIAR', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 15CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 20 CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 25 CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 30 CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 35 CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 40 CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE 45 CM', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('DOMO CHUNCAKE', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('CAJAS DE GALLETA', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
INSERT INTO item (name, category_id, companies_id, branch_id, price, active) VALUES ('BASE DORADA', (SELECT id FROM item_category WHERE name='ANAQUEL 4' AND companies_id=1 LIMIT 1), 1, 1, 0, 1);
SET @iid=LAST_INSERT_ID();
INSERT INTO item_attribute (item_id, companies_id, unit_id, cost_unit, stock_min, active) VALUES (@iid, 1, (SELECT id FROM unit WHERE name='PZ' AND companies_id=1 LIMIT 1), 0, 0, 1);
